### ISSUE TITLE
User can not able to altered todo list item.

### ISSUE THREAD

**Issue by bhavnapanchal** [bhavnapanchal/hivelocity_test#10]
In current version user is able to see todo list items only, there is no way user can alter it.
Eg. user is not able to create new, delete or edit existing ones.

For better experience user should have more control over todo list items.

**Comment by bhavnapanchal** [comment]
It is more like new feature so I am creating user story based on description.

[User story] : Able to alter todo list item.
- User want to add new todo item
- User want to delte existing todo item
- User want to edit existing todo item

Acceptance Criteria
- Able to do all alteration of todo list item.

Definition of done
- All required acceptance suppose to happen
- Functionality should work on all supported devices and criteria
- All unit test support to pass.

[Tasks]
- [ ] Create wireframe
- [ ] Create database schema
- [ ] Create API documentation 
- [ ] Create server side API
