### ISSUE TITLE
Should able to create user specific todo list.

### ISSUE THREAD

**Issue by bhavnapanchal** [bhavnapanchal/hivelocity_test#11]
In current version it is more like common todo list.
It should allow user to create their own todo list.

**Comment by bhavnapanchal** [comment]
[User story] : Able to create user specific todo list.

Right now it is common todo list, it should allow to create user specific.

- User want to create private todo list.
- User want to personalize their own todo list.
- User can share their own todo list with other selected users.
- User want to delete its own todo list.

Acceptance Criteria
- Use should able to create and manage their own todo list.

Definition of done

- All required acceptance suppose to happen
- Functionality should work on all supported devices and criteria
- All unit test support to pass.


[Tasks]
- [ ] Create wireframe
- [ ] Create database schema
- [ ] Create API documentation 
- [ ] Create server side API
